SRC_NAME = VNT-CLI
THISDIR = $(shell pwd)

all:

extract_test:

config_test:
clean:

romfs:
	   $(ROMFSINST) -p +x $(THISDIR)/vnt-cli /usr/bin/vnt-cli
           $(ROMFSINST) -p +x $(THISDIR)/vnt.sh /usr/bin/vnt.sh
