SRC_NAME = VNTS
THISDIR = $(shell pwd)

all:

extract_test:

config_test:
clean:

romfs:
	$(ROMFSINST) -p +x $(THISDIR)/vnts /usr/bin/vnts
        $(ROMFSINST) -p +x $(THISDIR)/vnts.sh /usr/bin/vnts.sh
