SRC_NAME = VNTS
THISDIR = $(shell pwd)

all:


config_test:

configure:

clean:

romfs:
	$(ROMFSINST) -p +x $(THISDIR)/vnts /usr/bin/vnts
        $(ROMFSINST) -p +x $(THISDIR)/vnts.sh /usr/bin/vnts.sh
